### ISSUE TITLE
Bad haproxy support

### ISSUE THREAD

**Issue by limpasha** [tarantool/tarantool-perl#25]
With HAProxy set up in front of tarantool the module starts consume 100% cpu when tarantool reloads. Here is sample configuration from production application:
```perl
DR::Tarantool::MsgPack::AsyncClient->connect(
		host		=> $cfg->{host},
		port		=> $cfg->{port},
		user		=> $cfg->{user},
		password	=> $cfg->{password},
		spaces		=> $cfg->{spaces},
#		request_timeout     => REQUEST_TIMEOUT,  # timeout on each request
		connect_timeout     => CONNECT_TIMEOUT,  # timeout on connect
		reconnect_period    => RECONNECT_PERIOD, # periods between connection attempts
                connect_attempts    => CONNECT_ATTEMPTS, # number of attempts between connection tries
		reconnect_always    => 1,
                lazy                => 1,
                on => {
                   connfail        => sub {warn "connection failed on $path: " . shift->error . "\n"},
                   reconnecting    => sub {warn "reconnecting to $path\n"},
                },
		sub {
			if (ref $_[0]) {
				$self->{_handler} = $_[0];
			}
			else {
				warn sprintf 'Cant connect to tnt %s:%s: %s', $cfg->{host}, $cfg->{port}, $_[0];
			}

			$cv->end;
		}
);
```

Stacktrace:
```
epoll_wait(7, {}, 64, 0)                = 0
epoll_wait(7, {}, 64, 0)                = 0
epoll_wait(7, {}, 64, 0)                = 0
```

Backtrace:
```
(gdb) bt
#0  0x00007f03c9ce3f33 in epoll_wait () from /lib64/libc.so.6
#1  0x00007f03c46f5c45 in ?? () from /usr/lib64/perl5/vendor_perl/auto/EV/EV.so
#2  0x00007f03c46fe2e6 in ev_run () from /usr/lib64/perl5/vendor_perl/auto/EV/EV.so
#3  0x00007f03c46ff4b2 in XS_EV_run () from /usr/lib64/perl5/vendor_perl/auto/EV/EV.so
#4  0x00007f03caf47815 in Perl_pp_entersub () from /usr/lib64/perl5/CORE/libperl.so
#5  0x00007f03caf45b06 in Perl_runops_standard () from /usr/lib64/perl5/CORE/libperl.so
#6  0x00007f03caeee0d8 in perl_run () from /usr/lib64/perl5/CORE/libperl.so
#7  0x0000000000400e74 in main ()
```

**Comment by limpasha** [comment]
I think we need here haproxy config file. I doubt haproxy can be used with tarantool.
